#include "2xml.h"
#include "util.h"
#include <assert.h>
#include <time.h>
/**@todo neaten up producing the XML, perhaps with a make tag vprintf wrapper */
/**@todo units needs escaping*/

static int indent(FILE *o, unsigned depth)
{
	while(depth--)
		if(fputc('\t', o) != '\t')
			return -1;
	return 0;
}

static int pnode(FILE *o, unsigned depth, const char *node, const char *fmt, ...)
{
	va_list args;
	assert(o && node && fmt);
	errno = 0;
	if(indent(o, depth) < 0)
		goto warn;
	if(fprintf(o, "<%s>", node) < 0)
		goto warn;
	assert(fmt);
	va_start(args, fmt);
	int r = vfprintf(o, fmt, args);
	va_end(args);
	if(r < 0)
		goto warn;
	if(fprintf(o, "</%s>\n", node) < 0)
		goto warn;
	return 0;
warn:
	warning("XML node generation, problem writing to FILE* <%p>: %s", o, emsg());
	return -1;
}

static int comment(FILE *o, unsigned depth, const char *fmt, ...)
{
	va_list args;
	assert(o && fmt);
	errno = 0;
	if(indent(o, depth) < 0)
		goto warn;
	if(fputs("<!-- ", o) < 0)
		goto warn;
	assert(fmt);
	va_start(args, fmt);
	int r = vfprintf(o, fmt, args);
	va_end(args);
	if(r < 0)
		goto warn;
	if(fputs(" -->\n", o) < 0)
		goto warn;
	return 0;
warn:
	warning("XML comment generation, problem writing to FILE* <%p>: %s", o, emsg());
	return -1;
}

static int signal2xml(signal_t *sig, FILE *o, unsigned depth)
{
	indent(o, depth);
	fprintf(o, "<signal>\n");
	pnode(o, depth+1, "name",      "%s",  sig->name);
	pnode(o, depth+1, "startbit",  "%u",  sig->start_bit);
	pnode(o, depth+1, "bitlength", "%u",  sig->bit_length);
	pnode(o, depth+1, "endianess", "%s",  sig->endianess == endianess_motorola_e ? "motorola" : "intel");
	pnode(o, depth+1, "scaling",   "%lf", sig->scaling);
	pnode(o, depth+1, "offset",    "%lf", sig->offset);
	pnode(o, depth+1, "minimum",   "%lf", sig->minimum);
	pnode(o, depth+1, "maximum",   "%lf", sig->maximum);
	pnode(o, depth+1, "signed",    "%s",  sig->is_signed ? "true" : "false");
	pnode(o, depth+1, "units",     "%s",  sig->units);
	indent(o, depth);
	if(fprintf(o, "</signal>\n") < 0)
		return -1;
	return 0;
}

static int msg2xml(can_msg_t *msg, FILE *o, unsigned depth)
{
	indent(o, depth);
	fprintf(o, "<message>\n");
	pnode(o, depth+1, "name", "%s", msg->name);
	pnode(o, depth+1, "id",   "%u", msg->id);
	pnode(o, depth+1, "dlc",  "%u", msg->dlc);

	for(size_t i = 0; i < msg->signal_count; i++)
		if(signal2xml(msg->signals[i], o, depth+1) < 0)
			return -1;
	indent(o, depth);
	if(fprintf(o, "</message>\n") < 0)
		return -1;
	return 0;
}


int dbc2xml(dbc_t *dbc, FILE *output, bool use_time_stamps)
{
	/**@todo print out ECU node information, and the standard XML header */
	time_t rawtime;
	struct tm * timeinfo;
	time(&rawtime);
	timeinfo = localtime(&rawtime);

	comment(output, 0, "Generated by dbcc (see https://github.com/howerj/dbcc)");
	if(use_time_stamps)
		comment(output, 0, "Generated on: %s", asctime(timeinfo));

	fprintf(output, "<candb>\n");
	for(int i = 0; i < dbc->message_count; i++)
		if(msg2xml(dbc->messages[i], output, 1) < 0)
			return -1;
	if(fprintf(output, "</candb>\n") < 0)
		return -1;
	return 0;
}

